version: '3.8'

services:
  widia:
    build:
      context: .
      args:
        - FRONTEND_ENV=${FRONTEND_ENV:-}
    ports:
      - "3000:8080"
    env_file:
      - backend/.env
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017}
      - DB_NAME=${DB_NAME:-widia_db}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - mongo
    networks:
      - widia-network
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.widia.rule=Host(`widia.io`)"
      - "traefik.http.routers.widia.entrypoints=http"
      - "traefik.http.routers.widia.middlewares=redirect-to-https"
      - "traefik.http.routers.widia-secure.rule=Host(`widia.io`)"
      - "traefik.http.routers.widia-secure.entrypoints=https"
      - "traefik.http.routers.widia-secure.tls=true"
      - "traefik.http.routers.widia-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.widia.loadbalancer.server.port=8080"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - widia-network

networks:
  widia-network:
  coolify:
    external: true

volumes:
  mongo-data: