version: '3.8'

services:
  widia:
    build:
      context: .
      args:
        - FRONTEND_ENV=${FRONTEND_ENV:-}
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017}
      - DB_NAME=${DB_NAME:-widia_db}
    depends_on:
      - mongo
    networks:
      - widia-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - widia-network

networks:
  widia-network:

volumes:
  mongo-data: